version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sistema
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 8812

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootsenha
      MYSQL_DATABASE: sistema
      MYSQL_USER: root
      MYSQL_PASSWORD: 8812
    ports:
      - "3306:3306"
